[package]
name = "bfv_ciphertext_addition"
type = "bin"
authors = ["Cedoor"]

[dependencies]
polynomial = {tag ="dev", git = "https://github.com/gnosisguild/enclave", directory = "packages/circuits/crates/libs/polynomial"}
greco = {tag ="dev", git = "https://github.com/gnosisguild/enclave", directory = "packages/circuits/crates/libs/greco"}