[package]
name = "crisp"
type = "bin"
authors = ["Cedoor"]

[dependencies]
polynomial = {tag ="armanc/safe-optimization", git = "https://github.com/gnosisguild/enclave", directory = "packages/circuits/crates/libs/polynomial"}
safe = {tag ="armanc/safe-optimization", git = "https://github.com/gnosisguild/enclave", directory = "packages/circuits/crates/libs/safe"}